function []=colorbar_community(K)
% Define the colorbar for communities.
%
% Version 1.0 
% 06-Nov-2019
% Copyright (c) 2019, Lingbin Bian

switch K
    case 3
        colorbar('Ticks',[1 2 3],...
                 'TickLabels',{'k=1','k=2','k=3'},...
                 'fontsize',16);
    case 4
        colorbar('Ticks',[1 2 3 4],...
                 'TickLabels',{'k=1','k=2','k=3','k=4'},...
                 'fontsize',16);
    case 5     
        colorbar('Ticks',[1 2 3 4 5],...
                 'TickLabels',{'k=1','k=2','k=3','k=4','k=5'},...
                 'fontsize',16);
    case 6
        colorbar('Ticks',[1 2 3 4 5 6],...
                 'TickLabels',{'k=1','k=2','k=3','k=4','k=5','k=6'},...
                 'fontsize',16);
    case 7
        colorbar('Ticks',[1 2 3 4 5 6 7],...
                 'TickLabels',{'k=1','k=2','k=3','k=4','k=5','k=6','k=7'},...
                 'fontsize',16);      
end

end