% This script analyses the inter-individual variation of CDE.
%
% Version 1.0
% 7-July-2021
% Copyright (c) 2021, Lingbin Bian
% -------------------------------------------------------------------------
clear
clc
%close all

colorvector=[1,1,0;0.78,0.38,0.08;0,0,1;1,0,0;0,1,0;0,0.5,0;0.5,0.5,0;1,0.5,0.5;1,0.5,0.31];    

% -------------------------------------------------------------------------
% Plot the effect of SRN on time variation of local maximum
figure    

load('Inter_ind_vari/max_location_n0.3162_vari0/vari_location.mat');

plot(localmax_ave(1,:),vari_localmax_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(1,:));
hold on    

load('Inter_ind_vari/max_location_n0.5623_vari0/vari_location.mat');
plot(localmax_ave(1,:),vari_localmax_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(2,:));
hold on 

load('Inter_ind_vari/max_location_n1_vari0/vari_location.mat');
plot(localmax_ave(1,:),vari_localmax_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(3,:));
hold on 


legend('SNR=10dB, DIIV=0', ...
    'SNR=5dB, DIIV=0', ...
    'SNR=0dB, DIIV=0','fontsize', 12)
    
title({'Effect of SNR on the local maxima';'of CDE curves'},'fontsize',16)
set(gca,'box','on')
set(gca,'fontsize',16)
xlabel('Time step','fontsize',16)
ylabel('Time deviation','fontsize',16)
set(gcf,'unit','centimeters','position',[6 10 14 11])
set(gca,'Position',[.15 .15 .75 .7]);
set(gca,'xtick',0:20:180)
set(gca, 'linewidth', 1.2, 'fontsize', 16, 'fontname', 'times')    
xlim([0,180]);    
ylim([0,10])    

saveas(gcf,'Inter_ind_vari/SNR_DIIV0_max.fig');

% -------------------------------------------------------------------------
% Plot the effect of DIIV on time variation of local maximum
figure

load('Inter_ind_vari/max_location_n0.5623_vari0/vari_location.mat');
plot(localmax_ave(1,:),vari_localmax_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(2,:));
hold on 

load('Inter_ind_vari/max_location_n0.5623_vari5/vari_location.mat');
plot(localmax_ave(1,:),vari_localmax_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(4,:));
hold on 

load('Inter_ind_vari/max_location_n0.5623_vari10/vari_location.mat');
plot(localmax_ave(1,:),vari_localmax_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(5,:));
hold on 

load('Inter_ind_vari/max_location_n0.5623_vari0_hrf/vari_location.mat');
plot(localmax_ave(1,:),vari_localmax_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(6,:));
hold on 

load('Inter_ind_vari/max_location_n0.5623_vari5_hrf/vari_location.mat');
plot(localmax_ave(1,:),vari_localmax_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(7,:));
hold on 

load('Inter_ind_vari/max_location_n0.5623_vari10_hrf/vari_location.mat');
plot(localmax_ave(1,:),vari_localmax_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(8,:));
hold on 


legend('SNR=5dB, DIIV=0', ...
    'SNR=5dB, DIIV=5', ...
    'SNR=5dB, DIIV=10',...
    'SNR=5dB, DIIV=0 (HRF)',...
    'SNR=5dB, DIIV=5 (HRF)',...
    'SNR=5dB, DIIV=10 (HRF)','fontsize', 12)


title({'Effects of DIIV and HRF on the local maxima';'of CDE curves'},'fontsize',16)
set(gca,'box','on')
set(gca,'fontsize',16)
xlabel('Time step','fontsize',16)
ylabel('Time deviation','fontsize',16)
set(gcf,'unit','centimeters','position',[6 10 14 11])
set(gca,'Position',[.15 .15 .75 .7]);
set(gca,'xtick',[20,50,80,100,130,160])
set(gca, 'linewidth', 1.2, 'fontsize', 16, 'fontname', 'times')

xlim([0,180]);    
ylim([0,18])  

saveas(gcf,'Inter_ind_vari/SNR5_DIIV_max.fig');

% -------------------------------------------------------------------------
% Plot the effect of DIIV on time variation of local maximum
figure

load('Inter_ind_vari/max_location_n0.3162_vari0/vari_location.mat');
plot(localmax_ave(1,:),vari_localmax_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(2,:));
hold on 

load('Inter_ind_vari/max_location_n0.3162_vari5/vari_location.mat');
plot(localmax_ave(1,:),vari_localmax_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(4,:));
hold on 

load('Inter_ind_vari/max_location_n0.3162_vari10/vari_location.mat');
plot(localmax_ave(1,:),vari_localmax_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(5,:));
hold on 

load('Inter_ind_vari/max_location_n0.3162_vari0_hrf/vari_location.mat');
plot(localmax_ave(1,:),vari_localmax_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(6,:));
hold on 

load('Inter_ind_vari/max_location_n0.3162_vari5_hrf/vari_location.mat');
plot(localmax_ave(1,:),vari_localmax_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(7,:));
hold on 

load('Inter_ind_vari/max_location_n0.3162_vari10_hrf/vari_location.mat');
plot(localmax_ave(1,:),vari_localmax_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(8,:));
hold on 


legend('SNR=10dB, DIIV=0', ...
    'SNR=10dB, DIIV=5', ...
    'SNR=10dB, DIIV=10',...
    'SNR=10dB, DIIV=0 (HRF)',...
    'SNR=10dB, DIIV=5 (HRF)',...
    'SNR=10dB, DIIV=10 (HRF)','fontsize', 12)


title({'Effects of DIIV and HRF on the local maxima';'of CDE curves'},'fontsize',16)
set(gca,'box','on')
set(gca,'fontsize',16)
xlabel('Time step','fontsize',16)
ylabel('Time deviation','fontsize',16)
set(gcf,'unit','centimeters','position',[6 10 14 11])
set(gca,'Position',[.15 .15 .75 .7]);
set(gca,'xtick',[20,50,80,100,130,160])
set(gca, 'linewidth', 1.2, 'fontsize', 16, 'fontname', 'times')

xlim([0,180]);    
ylim([0,18])  

saveas(gcf,'Inter_ind_vari/SNR10_DIIV_max.fig');
% -------------------------------------------------------------------------
% -------------------------------------------------------------------------
% Plot the effect of SRN on time variation of local maximum
figure    

load('Inter_ind_vari/min_location_n0.3162_vari0/vari_location.mat');

plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(1,:));
hold on    

load('Inter_ind_vari/min_location_n0.5623_vari0/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(2,:));
hold on 

load('Inter_ind_vari/min_location_n1_vari0/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(3,:));
hold on 


legend('SNR=10dB, DIIV=0', ...
    'SNR=5dB, DIIV=0', ...
    'SNR=0dB, DIIV=0','fontsize', 12)
    
title({'Effect of SNR on the local minima';'of CDE curves'},'fontsize',16)
set(gca,'box','on')
set(gca,'fontsize',16)
xlabel('Time step','fontsize',16)
ylabel('Time deviation','fontsize',16)
set(gcf,'unit','centimeters','position',[6 10 14 11])
set(gca,'Position',[.15 .15 .75 .7]);
set(gca,'xtick',0:20:180)
set(gca, 'linewidth', 1.2, 'fontsize', 16, 'fontname', 'times')    
xlim([0,180]);    
ylim([0,10])    

saveas(gcf,'Inter_ind_vari/SNR_DIIV0_min.fig');
% -------------------------------------------------------------------------
% Plot the effect of DIIV on time variation of local maximum
figure

load('Inter_ind_vari/min_location_n0.5623_vari0/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(2,:));
hold on 

load('Inter_ind_vari/min_location_n0.5623_vari5/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(4,:));
hold on 

load('Inter_ind_vari/min_location_n0.5623_vari10/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(5,:));
hold on 

load('Inter_ind_vari/min_location_n0.5623_vari0_hrf/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(6,:));
hold on 

load('Inter_ind_vari/min_location_n0.5623_vari5_hrf/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(7,:));
hold on 

load('Inter_ind_vari/min_location_n0.5623_vari10_hrf/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(8,:));
hold on 


legend('SNR=5dB, DIIV=0', ...
    'SNR=5dB, DIIV=5', ...
    'SNR=5dB, DIIV=10',...
    'SNR=5dB, DIIV=0 (HRF)',...
    'SNR=5dB, DIIV=5 (HRF)',...
    'SNR=5dB, DIIV=10 (HRF)','fontsize', 12)


title({'Effects of DIIV and HRF on the local minima';'of CDE curves'},'fontsize',16)
set(gca,'box','on')
set(gca,'fontsize',16)
xlabel('Time step','fontsize',16)
ylabel('Time deviation','fontsize',16)
set(gcf,'unit','centimeters','position',[6 10 14 11])
set(gca,'Position',[.15 .15 .75 .7]);
set(gca,'xtick',[20,50,80,100,130,160])
set(gca, 'linewidth', 1.2, 'fontsize', 16, 'fontname', 'times')

xlim([0,180]);    
ylim([0,18])  

saveas(gcf,'Inter_ind_vari/SNR5_DIIV_min.fig');

% -------------------------------------------------------------------------
% Plot the effect of DIIV on time variation of local maximum
figure

load('Inter_ind_vari/min_location_n0.3162_vari0/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(2,:));
hold on 

load('Inter_ind_vari/min_location_n0.3162_vari5/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(4,:));
hold on 

load('Inter_ind_vari/min_location_n0.3162_vari10/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(5,:));
hold on 

load('Inter_ind_vari/min_location_n0.3162_vari0_hrf/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(6,:));
hold on 

load('Inter_ind_vari/min_location_n0.3162_vari5_hrf/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(7,:));
hold on 

load('Inter_ind_vari/min_location_n0.3162_vari10_hrf/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(8,:));
hold on 


legend('SNR=10dB, DIIV=0', ...
    'SNR=10dB, DIIV=5', ...
    'SNR=10dB, DIIV=10',...
    'SNR=10dB, DIIV=0 (HRF)',...
    'SNR=10dB, DIIV=5 (HRF)',...
    'SNR=10dB, DIIV=10 (HRF)','fontsize', 12)


title({'Effects of DIIV and HRF on the local minima';'of CDE curves'},'fontsize',16)
set(gca,'box','on')
set(gca,'fontsize',16)
xlabel('Time step','fontsize',16)
ylabel('Time deviation','fontsize',16)
set(gcf,'unit','centimeters','position',[6 10 14 11])
set(gca,'Position',[.15 .15 .75 .7]);
set(gca,'xtick',[20,50,80,100,130,160])
set(gca, 'linewidth', 1.2, 'fontsize', 16, 'fontname', 'times')

xlim([0,180]);    
ylim([0,18])  

saveas(gcf,'Inter_ind_vari/SNR10_DIIV_min.fig');

% -------------------------------------------------------------------------
% Plot the effect of DIIV on time variation of local maximum
figure

load('Inter_ind_vari/min_location_n1_vari0/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(2,:));
hold on 

load('Inter_ind_vari/min_location_n1_vari5/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(4,:));
hold on 

load('Inter_ind_vari/min_location_n1_vari10/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(5,:));
hold on 

load('Inter_ind_vari/min_location_n1_vari0_hrf/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(6,:));
hold on 

load('Inter_ind_vari/min_location_n1_vari5_hrf/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(7,:));
hold on 

load('Inter_ind_vari/min_location_n1_vari10_hrf/vari_location.mat');
plot(localmin_ave(1,:),vari_localmin_location(1,:),'--ko',...
'LineWidth',1.2,...
'MarkerSize',7,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',colorvector(8,:));
hold on 


legend('SNR=0dB, DIIV=0', ...
    'SNR=0dB, DIIV=5', ...
    'SNR=0dB, DIIV=10',...
    'SNR=0dB, DIIV=0 (HRF)',...
    'SNR=0dB, DIIV=5 (HRF)',...
    'SNR=0dB, DIIV=10 (HRF)','fontsize', 12)


title({'Effects of DIIV and HRF on the local minima';'of CDE curves'},'fontsize',16)
set(gca,'box','on')
set(gca,'fontsize',16)
xlabel('Time step','fontsize',16)
ylabel('Time deviation','fontsize',16)
set(gcf,'unit','centimeters','position',[6 10 14 11])
set(gca,'Position',[.15 .15 .75 .7]);
set(gca,'xtick',[20,50,80,100,130,160])
set(gca, 'linewidth', 1.2, 'fontsize', 16, 'fontname', 'times')

xlim([0,180]);    
ylim([0,18])  

saveas(gcf,'Inter_ind_vari/SNR0_DIIV_min.fig');

