#!/bin/bash
# Without registration, the 1-level analysis results lack the reg file
# The reg generated by registration is copied to the .feat directory of 1-level analysis
# 
# Version 1.0
# 15-Jan-2020
# Copyright (c) 2020, Lingbin Bian

cd ../subjects
for subj in `cat subject.txt` ; do
   echo "===> Starting processing of $subj"
   mkdir $subj/MNINonLinear/Results/tfMRI_WM_LR/1st_LR.feat/reg
   cd $subj/MNINonLinear/Results/tfMRI_WM_LR
   cp Registration_LR.feat/reg/* 1st_LR.feat/reg
   cd ../../../..

   mkdir $subj/MNINonLinear/Results/tfMRI_WM_RL/1st_RL.feat/reg
   cd $subj/MNINonLinear/Results/tfMRI_WM_RL
   cp Registration_RL.feat/reg/* 1st_RL.feat/reg
   cd ../../../..
done

cd ../Shell_script_control